### ISSUE TITLE
Question: Is there an official style recommendation for "space before type"?

### ISSUE THREAD

**Issue by hgoebl** [basarat/typescript-book#116]
I've found different formatting for types:

    let x: number;
    let x:number;

Most of the code I read uses a space after the colon and AFAIK most of the code examples in the book are using this formatting as well. Unfortunately IntelliJ, (Php|Web)Storm code formatting default for TypeScript is using no space after the colon.

Is there an official recommendation?

If yes, would you mind adding this to your styleguide-page?

Thanks a lot. :rose:

**Comment by basarat** [comment]
> let x: number;

This is what I highly recommend. 

> If yes, would you mind adding this to your styleguide-page?

Will do :rose:

**Comment by hgoebl** [comment]
This helps me. I like your book, BTW.

**Comment by rcollette** [comment]
Good timing.  We're having a bit of a debate about this.  I'm curious what the justification is for putting a space after the colon.    I have two reasons why I don't like a space.

When initializing at declaration, and having space after the colon,  it reads to me like the value is being assigned to the type rather than the member/var.   I tend to think of a parameter/var and its type as an inseparable unit but this format doesn't convey that:

```
let variable: string = '';
```

I find it more natural like:
```
let variable:string = '';
```

The second reason is that WebStorm out of the box does not reformat with a space before or after the colon.  It's one less thing I have to have a developer change to get up and running. 

Any of these are just opinions but I do note that the Angular2 code style has a space after the colon and @basarat is stating so here, but I have yet to find reasoning behind it.

**Comment by nickroberts** [comment]
Everything that I've seen has spacing. It is easier to read, and doesn't look at jumbled together.

I look at it the same way as creating an object:

```
let coolObject = {
  property: 'value',
  another: 'property'
};
```

You wouldn't want something like this:
```
let hardToReadObject = {property:'value',another:'property'};
```

Spacing lets the eyes move along.

Also, IDEs should show that what comes after the `:` is the type, anyways.

Another thing, based on @basarat's recommendation, and all of the code styles on the angular.io site, I firmly suggest having spacing to the right of the `:`.

```
let recommended: boolean;
```

**Comment by onury** [comment]
@nickroberts Yes, I wouldn't want that..
I'd write:
```js
let easyToRead = { property: 'value', another: 'property' };
```
which I would confuse with:
```js
let still: This = { looks: 'like', the: 'value' };
```

```js
```
