### ISSUE TITLE
misleading const explanation

### ISSUE THREAD

**Issue by vujevits** [basarat/typescript-book#339]
The const keyword means that the variable cannot be re-assigned.

As the official TypeScript documentation states:
"This should not be confused with the idea that the values they refer to are immutable."

**Comment by basarat** [comment]
Already present : :rose: 

![image](https://user-images.githubusercontent.com/874898/32424476-dc4f7372-c300-11e7-93e7-ce028a4fe699.png)

https://basarat.gitbooks.io/typescript/content/docs/const.html

**Comment by vujevits** [comment]
I understand your reasoning at the end of this paragraph, but in my opinion this just gives the wrong idea for the less experienced developers. It can help people mix up immutability with the meaning of the **const** keyword in ES6 / TypeScript (only difference with let: cannot be re-assigned). 

A 'better' best-practice in my opinion is always using **const** instead of let, except when you need re-assignment. And understand immutability, for which there is no provided keyword in either javascript or TypeScript.

**Comment by mgoldberg524** [comment]
I realize this issue is over a year old but I think it's worth revisiting.

vujevits is absolutely correct that describing `const` as "allowing you to be immutable with variables" is incorrect and can be misleading to people reading this otherwise helpful page.

If you have:
```
const x = 7;
```

`x` is immutable because  `7` is a number and numbers in JavaScript are passed by value and cannot be mutated. It is not immutable because of the `const`. 

Also, I agree with vujevits's point that `const` should always be preferred over `let`, including in the case of `const x = {}`. `const` is not just for "magic literals". Please see the [Airbnb style guide section](https://github.com/airbnb/javascript/blob/master/README.md#variables--const) for more on this.
