### ISSUE TITLE
page layout glitch on gitbooks

### ISSUE THREAD

**Issue by guidorice** [basarat/typescript-book#514]
1st, thanks so much for this incredible resource!

I am noticing that every page I load on https://basarat.gitbooks.io/typescript
results in the content "jump" down when these badges load async. Maybe put it in a fixed height div so that doesn't happen?

![Screen Shot 2019-07-22 at 5 12 27 PM](https://user-images.githubusercontent.com/766758/61671265-0cbf7a00-aca4-11e9-9d00-4a7ea505f650.png)

**Comment by basarat** [comment]
Gitbook is not particularly ideal. I've had to bypass their (now legacy) plugin system to add a script. You can see the relevant commit. The glitch you are seeing is because of the 1000ms delay before first attempt to add this section.

In the attached commit I am now trying up front. But if the relevant section is not there, it will not show immediately. Happy to take a better PR :rose:

**Comment by guidorice** [comment]
Ah, I see what you mean. Thanks for the attempt anyways. I skimmed the gitbook docs and couldn't find any better way.
