### ISSUE TITLE
nominalTyping.html "Using Enums" method is more restrictive than "Using Interfaces" one

### ISSUE THREAD

**Issue by nahuel** [basarat/typescript-book#72]
The "Using Enums" method doesn't work for `number` types, but the "Using Interfaces" works ok for them:

```typescript
enum FooIdBrand {}
type FooId = FooIdBrand & number;
enum BarIdBrand{}
type BarId = BarIdBrand & number;

var fooId: FooId;
var barId: BarId;

fooId = barId; // NO error (wrong)
barId = fooId; // NO error (wrong)
```

Add a note explaining this Enum method restriction.

**Comment by basarat** [comment]
Indeed. Ill close it when I reread 🌹

**Comment by nahuel** [comment]
workaround described here: https://github.com/Microsoft/TypeScript/issues/202#issuecomment-184352626

**Comment by basarat** [comment]
> The "Using Enums" method doesn't work for number types, but the "Using Interfaces" works ok for them

Added a quick note before interfaces. FWIW can you describe a scenario where you need to nominally type *numbers*? Perhaps I can recommend a better way for you :rose:

**Comment by estaub** [comment]
@basarat, I use nominal types for database numeric primary keys a lot.

**Comment by basarat** [comment]
> I use nominal types for database numeric primary keys a lot.

use `type Foo = 0; type Bar = 1` etc ;) :rose:

**Comment by estaub** [comment]
@basarat, no, no, you misunderstand, I think.  You asked long ago for a "poster child" for typing numbers, I thought to use as a motivating case in the book.

> FWIW can you describe a scenario where you need to nominally type numbers?

I was referring to the value of the primary key field in each record, not a static value.  I was offering it as a case where nominally typing numbers is useful.

and I was offering this as a probably-common use case.  Another is for any measure where the unit - the value of "1" - is otherwise ambiguous:

`const speed: FeetPerFortnight`
vs.
`const speed: MetersPerSecond`

**Comment by basarat** [comment]
> You asked long ago for a "poster child" for typing numbers, I thought to use as a motivating case in the book.

Yup. Thanks. Makes sense. I will keep this poster child in mind :rose: :heart:
